### ISSUE TITLE
Request for converting int in config.json to bool

### ISSUE THREAD

**Issue by AvanindraC** [Shravan-1908/iris#5]
So I have a request that can the change_wallpaper duration be float? Like I kinda want a video background
![image](https://user-images.githubusercontent.com/77975448/134113013-460e3067-9616-47f4-98a4-f89ea94a39ce.png)

Here is what happens if I give the value as float

**Comment by shravanasati** [comment]
Your feature request has been accepted, but instead of allowing float values as `change_wallpaper_duration`, a better and more extensible approach has been taken - supporting any type of duration. Examples: `5s` `30s` `5m` `26m45s` `1h` `2h30m` `5h8m19s` and likewise.

Added via commit https://github.com/Shravan-1908/iris/commit/807a60b653961c7bc4e7fe4365de5f0d9cbdb7f2 .
